apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ztp-spoke-01
  namespace: ztp-spoke-01
  labels:
    cluster-name: ztp-spoke-01
spec:
  config:
    dns-resolver:
      config:
        server:
          - 192.168.50.1
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.50.100
              prefix-length: 24
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
        name: ens3
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.50.2
          next-hop-interface: ens3
          table-id: 254
  interfaces:
    - macAddress: 52:54:00:AA:BB:CE
      name: ens3
