apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ztp-spoke-01
  namespace: ztp-spoke-01
  labels:
    cluster-name: ztp-spoke-01
spec:
  config:
    dns-resolver:
      config:
        search:
          - 192.168.50.140.nip.io
        server:
          - 192.168.50.1
    interfaces:
      - ipv4:
          address:
            - ip: 192.168.50.140
              prefix-length: 24
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
        name: enp1s0
        state: up
        type: ethernet
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.150.1
          next-hop-interface: enp1s0
          table-id: 254
  interfaces:
    - macAddress: '54:52:00:01:05:40'
      name: enp1s0
