apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: ztp-spoke-01
  namespace: ztp-spoke-01
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
#  proxy:
#    httpProxy: <proxy>
#    httpsProxy: <proxy>
#    noProxy: <domain-or-ips-comma-sepparated>
#  additionalNTPSources:
#    - 0.rhel.pool.ntp.org
  clusterRef:
    name: ztp-spoke-01
    namespace: ztp-spoke-01
  sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCglkbsUTUr3aKzfOwqw+wTX78eisTJ0QJ7mYpanrSajFr+1PZIi/VHbIWSuzDzJ2S6FV6rOlnWry+70kGeimoW4bT/IsCxu/dL522qzxWUSuGKOLzG5sehTeQ99uKFAJWRGn5B/enmiEWl1hsSArnGPh1b4Ujn6S+EivNTxlb2uG8D2c00ycUNZPpexKd2S10ft76uVjAFv08/QAmzPzGHxu0b9MiSLlKQpNV85Lb7b4mM91ZsiJrIhQ9Rys8FmS5HI3ofzvfVNlwx2Pkpf/ou6gf5vSsKa8ZOw7THteBbMFGS7Bmdigsu6+D1U7ijSj74GddlD0b0c8swt8dBu3/yuLWvnzzlC8No7A3UxAPd6pwsUBxGZVQLcbHXUSwE7BY5ebBLV5Br2huwgG5Q4bBNDSp3FdJclepFy8j1AXNYmw7QtsQNQYgfFXPWmW36AI29suzLOqQu+dPzeM6A8Tpd7rAdRvyeACZleWGqLIU7xLoxlxw66d/zkNkOMYl4vas='
  agentLabelSelector:
    matchLabels:
      cluster-name: ztp-spoke-01
  pullSecretRef:
    name: pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: ztp-spoke-01
# User for modify ignition during discovery
#  ignitionConfigOverride: ''
