apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: ztp-spoke-01
  namespace: ztp-spoke-01
  labels:
    networkType: static
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  clusterRef:
    name: ztp-spoke-01
    namespace: ztp-spoke-01
  sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/qqEy/Ev6XZhdJ9R0yqGAoYhekXBWhkVMBhhbCq66r+Nl8vpgjlpASrHGNMpwtUHRZpo6yfJaM7qMLskndbMW1Yq77Le3Bm2M7M1VEmw7if1kpiyXCLPAcjRxgtph74v8TQUdg5o57MaUIxbRzSHOpd7TkvpwlK62WOQG0aE1wIgkAOaZdLnPpJluSTOVQvbOEqyF3ukUM5erbNrit1xRfRCvpWTMvWkTjtKwr5PjBuuG3ZtpmF9i7bV7sky0863AyaXwHbqKNanfZB6B/2FNRQvL4qF18J0wlroUpzPYVXpxjaEt79OuoNZZ8+mCXI4TlCga8oRQQihJ0klTkFwt ansible-generated on ralvares'
  agentLabelSelector:
    matchLabels:
      cluster-name: ztp-spoke-01
  pullSecretRef:
    name: pull-secret
  cpuArchitecture: x86_64
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: ztp-spoke-01
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capi-provider-role
  namespace: ztp-spoke-01
rules:
  - verbs:
      - '*'
    apiGroups:
      - agent-install.openshift.io
    resources:
      - agents
