apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "ztp-spoke-01"
  labels:
    infraenvs.agent-install.openshift.io: "ztp-spoke-01"
  name: ztp-spoke-01
  namespace: ztp-spoke-01
spec:
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    address: redfish-virtualmedia+http://192.168.50.1:8000/redfish/v1/Systems/51af2ccf-d63a-4838-8e6f-7951afd38fe5
    credentialsName: bmc-secret
    disableCertificateVerification: true
  bootMACAddress: '52:54:00:20:99:f6'
  bootMode: UEFI
  online: true
