apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
    visible: 'true'
  name: "openshift-4.14.0"
spec:
  releaseImage: "quay.io/openshift-release-dev/ocp-release:4.14.0-x86_64"
