apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-1 Policy and Procedures
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    open-cluster-management.io/policy-set: rhacs
  name: policy-acs-operator-central
  namespace: default
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-acs-operator-central
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: stackrox
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: rhacs-operator
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: rhacs-operator-group
              namespace: rhacs-operator
            spec: {}
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: rhacs-operator
              namespace: rhacs-operator
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: rhacs-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
        - complianceType: musthave
          objectDefinition:
            apiVersion: platform.stackrox.io/v1alpha1
            kind: Central
            metadata:
              name: stackrox-central-services
              namespace: stackrox
            spec:
              central:
                exposure:
                  loadBalancer:
                    enabled: false
                    port: 443
                  nodePort:
                    enabled: false
                  route:
                    enabled: true
                persistence:
                  persistentVolumeClaim:
                    claimName: stackrox-db
              egress:
                connectivityPolicy: Online
              scanner:
                analyzer:
                  scaling:
                    autoScaling: Disabled
                    maxReplicas: 5
                    minReplicas: 2
                    replicas: 1
                scannerComponent: Enabled
        remediationAction: enforce
        severity: medium
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-acs-operator-central-placement
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: In
              values:
                - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-acs-operator-central-placement-binding
  namespace: default
placementRef:
  name: policy-acs-operator-central-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-acs-operator-central
    apiGroup: policy.open-cluster-management.io
    kind: Policy
